Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"
  config.vm.boot_timeout = 3600

  config.vm.define "mcordesS" do |control|
    control.vm.hostname = "mcordesS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.gui = false
      v.name = "mcordesS"
      v.memory = 2048
      v.cpus = 2
    end
    control.vm.provision "shell", inline: "bash /vagrant/scripts/server_1_setup.sh"
  end
end
